package com.yourcompany.core.services;

import org.jetbrains.annotations.NotNull;

import com.yourcompany.core.exceptions.OpenAIChatServiceException;

/**
 * Service contract used to obtain responses from the OpenAI Chat Completions API.
 */
public interface OpenAIChatService {

    /**
     * Sends the supplied prompt to the configured OpenAI endpoint and returns the response text.
     *
     * @param prompt the end-user prompt that should be sent to the model
     * @return the textual response generated by the OpenAI model
     * @throws OpenAIChatServiceException if the request cannot be completed or the API returns an error
     */
    @NotNull
    String getChatResponse(@NotNull String prompt) throws OpenAIChatServiceException;
}
